name: Build and Deploy Angular App to CloudFront
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: www.simegnewmulu.tech
      DIST: dist
      REGION: us-east-1
      DIST_ID: E1V3HWCXCURVFR

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          npm install -g @angular/cli
          npm ci

      - name: Build Angular App
        run: ng build

      - name: Deploy to S3 Bucket
        run: |
          aws s3 sync --delete ${DIST} s3://${BUCKET} --region ${REGION}

      - name: Create CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${DIST_ID} \
            --paths "/*" \
            --region ${REGION}
